### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by isaireyesp** [SistemasTecTlaxiaco/actividad-1-infografia-isaireyesp#1]
[Infografia sobre Trabajo Remoto Ilustrado Azul (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-isaireyesp/files/14249771/Infografia.sobre.Trabajo.Remoto.Ilustrado.Azul.1.pdf)

**Comment by josealfredo79** [comment]
Calificacion cual es ???

**Comment by 2003lulu** [comment]
20/20

**Comment by josealfredo79** [comment]
Falta la bibliografia de la cual se obtuvo la informacion...

**Comment by isaireyesp** [comment]
si las tiene están en el apartado de referencias bibliográficas

**Comment by isaireyesp** [comment]
![image](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-isaireyesp/assets/101884557/6cab8906-2898-4d58-8d1b-4d71977458de)
